### ISSUE TITLE
Nirnroot naming

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#112]
What should we call nirnroots? Just "Nirnroot"? Should we number them? Name them?

**Comment by Muggyfox1** [comment]
The nirnroute handbook gave each nirnroot a nickname. we could copy the names from there.

**Comment by Muggyfox1** [comment]
Meemaw is working on transcribing names from the nirnroute handbook.
We can probably take it from his excel sheet and put it into our Json when he's done.
