### ISSUE TITLE
Nirnroute page

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#126]
How TF are we gonna do the nirnroute? just use a separate doc in teh style of the guides?

**Comment by MichaelEbert** [comment]
put it in the guide page makes it really long...

**Comment by Muggyfox1** [comment]
Just spitballing ideas here.
do you think we could crunch the nirnroot pictures in the name area on hover?

If we put it in guide.html, we could stick the pictures on the sidebar?

or just link directly to the picture w/ a hyper link?

**Comment by MichaelEbert** [comment]
I think on hover photos would be too small. We could put them behind a link, and have them open in the sidebar.

**Comment by MichaelEbert** [comment]
MeemawHustlin: The nirnroute could have a "circuit" option that puts you into a special view for following the exact path. It would make all the other vectors transparent except for the current one you are on, and you can use left/right arrows to jump from point to point along the path. Each nirnroot you are currently looking at shows the images/corn tip around the edges of the screen since the map itself would center on each pair of current nirnroot -> next nirnroot
