### ISSUE TITLE
Checklist formatting - fix subsection names and add vertical dividers

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#14]
Formatting wise, centering the names of the objective categories and their light gray subsection names would visually distinguish them since currently the greyed out sections look like quests you can't do or something. Some sort of vertical divider between things might distinguish the check boxes at a glance from the objectives to their right as well. Overall the checklist is fantastic, also nice job right aligning the checkboxes for more visual clarity.

**Comment by Muggyfox1** [comment]
![image](https://user-images.githubusercontent.com/47337746/161828022-d171d59c-6d9b-455e-a88f-578fe2bc6507.png)
Is this the kind of formatting we're looking for?
