### ISSUE TITLE
Add hotkeys to speech box

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#16]
Shoudl be able to press space - or, on mobile, tap - and have it read out the next line

**Comment by Muggyfox1** [comment]
Working on this

**Comment by Muggyfox1** [comment]
update: the hotkey is working, moving to the next line and reading it out loud. Touches need some testing (can't seem to get it to work for me).
Also, will try and figure out a way to keep focus on the part being read rather than spacebar just leaving focus in the middle of the page.
