### ISSUE TITLE
Class reset calculator requirements

### ISSUE THREAD

**Issue by PeterQLee** [MichaelEbert/OblivionProgressTracker#165]
## Calculator Logic
- [x] Attribute (e.g., Strength) level calculations
- [x] Skills level calculations
- [x] Underflow logic

## Quality of life 
- [x] gray out checkboxes when number of specialized skills = 7.
- [x] Favoured attributes 1 & 2 should be mutually exclusive.

**Comment by MichaelEbert** [comment]
Fixed in #166 .
