### ISSUE TITLE
Do we need [Npc],[book],etc tags? can players figure this out on their own?

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#197]

**Comment by MichaelEbert** [comment]
Yeah we can probably do this. Get thoughts from others first

**Comment by MichaelEbert** [comment]
they might be useful for first time users

**Comment by MeemawHustlin** [comment]
I think the less [Objective] labels the better personally as it would fit in better with the guide's pre-website formatting and looks less cluttered, although I suppose it is typically bad UI design to have color coding exclusive labelling in the case of people who are colorblind and whatnot. I could go either way on this, alternatively perhaps a toggleable formatting option to display explicit objective tags if it isn't super time consuming to implement.
