### ISSUE TITLE
A quick "how to" section at the top of the guide about how to use the interactive checklists primary features.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#198]
Possibly include a section at the top of the guide that has instructions  on how to use the guide's various features, with a generic save file number tracker box, checkboxes, terms at the top to teach the runner how to interact with the guide properly. Also a key showing what the various colored texts indicate.

**Comment by MichaelEbert** [comment]
Maybe a new homepage that lists the how to and stuff. There are enough features that it needs an explanation page now.

**Comment by MeemawHustlin** [comment]
It could be convenient to put the "how to" as another iframe icon next to the map and TOC for easy reference without losing your spot in the guide having to scroll to find it at the top. This doubles as a way to have it automatically be loaded in at the start, showing the user immediately how the iframe works in tandem with the guide itself.

**Comment by MeemawHustlin** [comment]
This has been done for awhile with the implementation of the Help tab in the guide info box.
