### ISSUE TITLE
Reorganizing the top tabs of the overall site for better navigation.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#199]
I think the current tabs (Checklist, Speedrun, Casual, Map, Settings, Wiki) would be better organized like this:

- Checklist (since this is the primary thing people will be using regardless of play style)
- Guide, with dropdowns for the Speedrun and Casual versions (assuming table of contents navigation is implemented into the individual guides.)
- Map (with dropdowns for Main Map and Nirnroute)
- Wiki (with a new dropdown option for requirements)
- Settings

What does everyone else think? My main goal is to condense the different guides all under a guide tab, that way we can future proof by putting old revisions of guides in some sort of "Archive" at the bottom of the guide list.

**Comment by MichaelEbert** [comment]
Sounds mostly good. The one thing im wondering about is the guide tab.
I like having casual as a top level option as speedrun players are probably going to invest enough time to figure out the UI, while casual players are not. Having the causual guide as a top level makes it both accessible and implies "we care about the casual community". This is something that I really liked about the v3 materials: you had casual as a top level guide along with the speedrun stuff.
Another thought is putting both guides on a  single tab would mean re-doing the Table of contents, as thats currently just a dropdown.

**Comment by MeemawHustlin** [comment]
The main thing I'm thinking is mostly that the casual guide tab might be in the way of speedrunners to an extent since it is between all the other tabs they need access to but I do see your point about the visibility of the casual materials. Maybe we should get some more input on this particular part from other community members.

**Comment by MeemawHustlin** [comment]
Going to close this issue since the navbar was overhauled recently. As far as casual guide visibility goes, we can just put text at the top of the speedrun guide that tells the user to navigate to the casual guide if they want an easier route to follow.
