### ISSUE TITLE
[Guide UI] Table of Contents

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#201]
Having the table of contents navigation moved from being in a dropdown under the guide tab to being a collapsible menu on the left side of the screen (like how google docs has it) would be a lot cleaner of a way to go through the route quickly. Ideally we could have the table of contents have primary split sections as well as the smaller subsplits for things like the phases of the skill grind.

**Comment by MichaelEbert** [comment]
THeoretically I like this idea. dropdown at the top can be kinda inconvenient and not really any way to do sublevels.

3 column layout is difficult for small screens and making it look good when resized will take *effort*, and probably not doable before v4, unless its a dealbreaker.

May be able to rig up something ugly and basic though.

**Comment by MeemawHustlin** [comment]
Ah yeah totally forgot about needing everything to resize properly. Ugly and basic works, the main thing I'm hoping for is to have sublevels mostly (and just so that the dropdown doesn't disappear when the mouse leaves the menu) so even if it has to temporarily cover the entire left side of the screen or something that's no big deal. This entire feature isn't super important right now anyway, def a lower priority since we already have something close enough with the current tab system.
