### ISSUE TITLE
Images brought over to the second window don't resize automatically.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#204]
I think the best solution to this problem would be to have any images that are brought over to the second window be automatically sized to fill the container rather than be their normal full size.

**Comment by MichaelEbert** [comment]
wow firefox does that automatically :/

**Comment by MichaelEbert** [comment]
gotta go in and use JS to tinker with the resulting page probably UGH

**Comment by MeemawHustlin** [comment]
This was closed but as far as I can tell, at least on chrome, this is still an issue with images. The screenshots of save clip locations in particular are a pain because of how large they are compared to the box. One potential idea to mess with would be having different types of content automatically resize the iframe window, such as the map making it wider than normal, or wiki pages being the minimum width before they look unreadable.

**Comment by MichaelEbert** [comment]
Damn thought I fixed that. I'll have a look.
