### ISSUE TITLE
PRCLive socials/github project link somewhere on the site.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#205]
It would be good to have links to areas where people can contribute to the project (most useful would be this Github and the Discord server) somewhere on the website.

We obviously want to avoid a bloated/cluttered UI so rather than putting them in a new area along the bottom or something I think the best spot for a link to stuff like this would a small Community tab on the far right. Having a similar thing on the far left (the PRCLive logo) as a link to whatever eventual homepage we implement could be useful as well.

**Comment by MichaelEbert** [comment]
Can go in templates/footer.html which we then apply to all pages

**Comment by MeemawHustlin** [comment]
This was added several pull requests ago by adding the PRCLive corn icon at the top left of the navbar.
