### ISSUE TITLE
[Map UI] Map icons to check off on single click, selected for travel estimates with double click.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#206]
We'll need to be checking off map icons way more often than checking the fast travel time between locations, so I think double click works better for more obscure features than single click. Single click will making checking off feel much smoother.

**Comment by MichaelEbert** [comment]
Having both 'select' and 'check off' bound to the same mouseclick is causing issues.

problem that comes up is that double click does a single click as well. so if you want to select something it also checks/unchecks it which is really confusing, especially with gates which have 3 selection states (undiscovered-discovered-closed). 

Maybe bind like right-click or ctrl-click to the doubleclick as well. Need to keep doubleclick for touchscreen users. 

or maybe click selects, and clicking on the background map area deselects.

**Comment by MeemawHustlin** [comment]
Deselect via clicking on an empty area of the map seems like the best option. I'd almost say the next best option is to completely remove the click to select feature in the normal map so that we can prioritize the main function of checking off locations if it is complicating things. Do you mean that double click is the only way touch screen users could check things off? They can't single click to interact at all?
