### ISSUE TITLE
[Map UI] Easy way to reset the whole map.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#208]
Being able to clear the entire map without having to wipe the entire progress file might be nice, especially during the routing phase. It would likely need to be pretty out of the way and have some sort of verification before doing so.

**Comment by MichaelEbert** [comment]
Since this is for routing, does it matter if we clear all the nirnroots, even the ones that aren't in the nirnroute?

**Comment by MeemawHustlin** [comment]
I think just wiping the entire map icons, gate closing, and overworld nirnroot states would be sufficient.

**Comment by MeemawHustlin** [comment]
This issue was fixed awhile ago, closing this one since it was recently improved upon again by Muggy.
