### ISSUE TITLE
[Map UI] Double clicking on the map highlights the text above it.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#211]
Minor issue, but I remember someone mentioning in chat that it was weird how the text above the map is selected when double clicking. This isn't an essential fix as it doesn't make the map function any differently but figured I would mention it here.

**Comment by MichaelEbert** [comment]
Yeah, thanks. These chrome-specific issues are good to mention since I primarily use firefox
