### ISSUE TITLE
[Map] Need to make one final TSP for locations to account for new route logic.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#213]
We now explore the map early enough that several locations are no longer discoverable at the time that we do the TSP for locations:

- Serpent's Trail
- 6 more city fixed gates (Chorrol Gate, Anvil Gate, Skingrad Gate, Bravil Gate, Leyawiin Gate, Cheydinhal Gate). **Kvatch stays in the path, and Bruma Gate was already excluded and should remain excluded.**
- The other 11 misc. fixed gates. **This includes the fort sutch gate (which I can’t remember if we actually call it that anymore or if it is just another generic fixed gate.)**

I'll be asking Yeti about this soon.

**Comment by MichaelEbert** [comment]
While we are regenerating TSPs, we should test approximate distance at which running to the next nirn is fster than warping to it. ex: nirn #222, might be faster to just walk than to open up map and go through loading screen and get reoriented. https://michaelebert.github.io/OblivionProgressTracker/nirnroute.html?tspId=222

**Comment by MeemawHustlin** [comment]
I'll leave this open until further testing is done on your point about unnecessary fast travels, just updating to say I have added in yeti's most recent TSP on a pending pull request removing the locations described in the initial post.

**Comment by MeemawHustlin** [comment]
The new TSP path has been implemented. We can revisit the idea of optimizing manual travel vs fast travel at a later point but the primary focus of this issue has been resolved.
