### ISSUE TITLE
[Nirnroute UI] Auto-checking Nirnroots as we advance through the circuit.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#214]
Currently it takes one click to go to the next nirnroot, and another double click on the previous root to check it off. Ideally, this would all be done in a way that the user stays on the Next button and just keeps clicking that to check off plants (we could also add arrow key functionality for higher QoL so they don't have to keep the mouse over the small Next button.)

**Comment by MichaelEbert** [comment]
If the user clicks "prev", should that uncheck the nirn?

**Comment by MeemawHustlin** [comment]
I think that would work the best, and maybe just a setting to toggle autochecking on/off with it on by default since casual players may not use the circuit.
