### ISSUE TITLE
Nirnroot text is green instead of blue

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#233]
I believe it was blue in a recent version of the guide but somehow it has turned green and blends in with NPC tags too much.

**Comment by Muggyfox1** [comment]
I think it was supposed to be seagreen the whole time, the commit that added it was 14 months old. :\ 
![image](https://user-images.githubusercontent.com/47337746/200195198-b6f8467e-fdf4-40b1-a4f3-ce0ee7e3fa4a.png)

in the interest of seeing what it looks like as blue:
![image](https://user-images.githubusercontent.com/47337746/200195397-a4457ce6-a340-44a7-bc4c-bebc2f322554.png)

Thoughts? do we want it blue? or another color?

I tried some other kinds of colors like cyan or other greens, but they feel too similar. So I think blue is the way to go.

**Comment by MeemawHustlin** [comment]
The hex value used on the google doc version is #1155cc which makes it slightly less intense looking than a normal link color. I imagine seagreen was chosen before to avoid it looking like the glitch links, but I think we should probably recolor glitches to be something other than a generic link color in the future anyway.

**Comment by Muggyfox1** [comment]
Here it is with that hex code as the color: 
![image](https://user-images.githubusercontent.com/47337746/200196924-74ea5c8e-3cf8-41fd-98b6-116c4635b985.png)

**Comment by MeemawHustlin** [comment]
I think that will look fine, especially after we change glitches to have a unique link color, also people won't look at text that doesn't say Nirnroot and think it is a Nirnroot either way.

**Comment by Muggyfox1** [comment]
I'll have it added in the next merge request I make.
