### ISSUE TITLE
Glitch class for easier implementation of glitches into the guide

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#235]
Glitches are one of the only frequently used interactive text elements that does not have its own custom span, requiring manual linking to its wiki article. Ideally glitches would go from something like this:

`Face the wall and <a href="https://prclive.run/wiki/Oblivion:Save_Clipping" target="_blank">Save Clip</a> through the corner.`

to this:

`Face the wall and <span class="glitch">Save Clip</span> through the corner.`

so we can have more control over the formatting and updating of glitch links if we need to, along with improving the readability of the html code for the guide. The thing that would make glitches different from other classes is they would need to have a list of potential inner text values (ignoring case) that redirect to the correct glitch page since their wording is not identical every time like an NPC or quest name would be. Something along these lines:

```
{"version":2,"weight":0,"name":"glitch","elements":[
    {"id":"Save Clip", "link":"https://prclive.run/wiki/Oblivion:Save_Clipping", "terms":["Save Clip", "Save Clipping"]}
    {"id":"Class Reset", "link":"https://prclive.run/wiki/Oblivion:Class_Reset", "terms":["Class Reset", "Race Reset", "Birthsign Reset"]}
]}
```

**Comment by MichaelEbert** [comment]
The way we would do it is specify the id in the link itself.
```html
<span class="glitch" clid="saveclip">clip</span> through the wall and then do a <span class="glitch" clid="classreset">birthsign reset</span>
```
I just need to edit the code a bit to use the original term instead of always replacing it

**Comment by MeemawHustlin** [comment]
Small idea to note, I think visually it might look best if this glitch class were to still have the hover/cursor to indicate clicking, but were just a dotted underline or something else equivalently subtle to not distract from the checklist terms. Having too many things be bold/colored will end up being too busy looking.
