### ISSUE TITLE
properly implement faction ranks

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#261]
Current implementation just checks for any rank instead of max rank.

**Comment by MichaelEbert** [comment]
take a look at valarnin's code and copy from there

**Comment by valarnin** [comment]
Specifically this code:
https://github.com/valarnin/oblivion-save-reader/blob/main/test.js#L718-L730

The `factions` constant is defined here:
https://github.com/valarnin/oblivion-save-reader/blob/main/save/constants.ts#L1346-L1366
