### ISSUE TITLE
Add NPC data

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#28]
current NPC minipages don't work on NPCs that don't have entries in npc.json. So add? i guess?

**Comment by MichaelEbert** [comment]
this will require implemmenting findCell priorities, or be aware that there may be multiple cells with the same formID.

**Comment by MeemawHustlin** [comment]
This is a super old issue that was created prior to the implementation of the custom wiki pages, which will replace the need for NPC data held in minipages. Closing this, feel free to reopen if you feel it is still relevant.
