### ISSUE TITLE
Map Icon marking system overhaul

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#285]
The in-game undiscovered inverted color icons for places would work better, and then checking them off just turns them to the normal icon, with check marks indicating things like closed gates, nirnroots, wayshrines, and heaven stones.

**Comment by MichaelEbert** [comment]
@MeemawHustlin  can you update the instructions to reflect this?

**Comment by MeemawHustlin** [comment]
Yeah I can add new instructions in my next PR.
