### ISSUE TITLE
NPCs no longer have question marks, need to update help page wording and figure out if this was intentional

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#303]
I like the way it looks having the NPCs not have the question marks since it is less busy overall, maybe I just can't remember what it looked like before because I'm tired

**Comment by MichaelEbert** [comment]
it's intentional.
```
if(!cell.hive.class.containsUserProgress){
        defaultFormatting &= ~CELL_FORMAT_SHOW_CHECKBOX;
        defaultFormatting &= ~CELL_FORMAT_NAMELINK_SEPARATE_HELP;
    }
    ```
 if the class doesn't contain user progress, we link the name instead of a separate help icon.

**Comment by MeemawHustlin** [comment]
I've been looking at this code too long lol.

I'll update the help page so it doesn't say npcs have question marks.
