### ISSUE TITLE
General performance issues with checklist

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#310]
Is anyone else getting a decent amount of lag/input delay when clicking several checklist items off in a row? For me it seems like it is slowing down pretty hard.

**Comment by MichaelEbert** [comment]
works fine for me

**Comment by MichaelEbert** [comment]
i see it. will give it a look.

**Comment by MichaelEbert** [comment]
it's due to layout invalidation caused by the combination of the `height:100vh` in body, and changing the subtotals at the top.

**Comment by MeemawHustlin** [comment]
performance has been fixed
