### ISSUE TITLE
User settings don't initialize properly for brand new user.

### ISSUE THREAD

**Issue by MeemawHustlin** [MichaelEbert/OblivionProgressTracker#320]
I had someone test the checklist on chrome on their computer, which had never loaded the website before, and the settings were all blank and the checklist/progress bar wouldn't initialize properly. I think we ran into this in the past, either way it's back again.

**Comment by MichaelEbert** [comment]
just pushed a hotfix for the settings page. that might fix it

**Comment by MeemawHustlin** [comment]
I'll have someone check this who has never been to the site before.

**Comment by MichaelEbert** [comment]
fixed
