### ISSUE TITLE
better dialogue

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#4]
MeemawHustlin: I'm thinking we could format dialogue trees to be way more visually obvious how to navigate them since currently they are just a barrage of options. This would make the depth within each tree easier to identify quickly along with getting rid of the redundant "Dialogue: ..." line at the front since the formatting would convey it.
https://media.discordapp.net/attachments/644112615718780940/882126522104832050/unknown.png

**Comment by MeemawHustlin** [comment]
A quick update on this, I have begun re-formatting the non-interactive draft of the v4 guide to include this style. Mostly wondering if there is an easy way to make non-italicized arrows as shown here, but italicized text for the dialogue (I've opted to not use quotation marks around text, although I may want to change this to account for Advance Predetermined Dialogue type commands). I've also found that making the dialogue text a lighter grey makes it more visually separate from the core instructions.
