### ISSUE TITLE
category margin-left is obnoxious on mobile

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#40]
2em is huge when the font size is large. 2% is about the same at 1080p, but at high resolutions it becomes really large.

**Comment by Muggyfox1** [comment]
I might take a try at this later. 

I think it would be a good idea to use media queries for this issue.
https://www.w3schools.com/css/css_rwd_mediaqueries.asp

**Comment by MichaelEbert** [comment]
Take a look at CSS3 functions, that way it scales cleanly for all resolutions instead of having to choose an arbitrary one.

**Comment by MeemawHustlin** [comment]
This appears to have been fixed awhile ago and we forgot to close this one.
