### ISSUE TITLE
Speech Reads Sublists Twice

### ISSUE THREAD

**Issue by lukepk** [MichaelEbert/OblivionProgressTracker#43]
Speech will now read every line in a sublist, but it will also read the entire sublist container (including all the sublist contents) as a single part first.

Fixing this is probably going to require checking for this case and ignoring some of the text grabbed from the top level item (NOTE: ignoring text from all sub-elements won't work due to use of \<span> tags. Need to remove sublist content specifically)

https://github.com/MichaelEbert/OblivionProgressTracker/blob/master/autoread.js#31

**Comment by Muggyfox1** [comment]
working on this.

we can avoid this issue by formatting sub lists differently.

how we're currently doing it
![current way](https://user-images.githubusercontent.com/47337746/135183747-ee929ba0-ee29-4dc8-8cb5-ac857e40eb12.png)

if we format sub lists this way instead, we can avoid the double reading and not have to rewrite/write more edge cases on the speech box

![new way](https://user-images.githubusercontent.com/47337746/135183788-a38c4cda-6164-4d6a-9f40-bb0a0baab4cf.png)

**Comment by MichaelEbert** [comment]
I don't like having the sublist be a separate entity. It's also technically not permitted by spec.

I think it should be easy enough to separate out the sublist text. Just read the fragments up to the first ol instead of the entire line text.
