### ISSUE TITLE
Style Elements from Collapsible Section Titles also affect non-collapsible sections

### ISSUE THREAD

**Issue by lukepk** [MichaelEbert/OblivionProgressTracker#51]
Most notable on the minipages, but also in the Glitches and casual guide pages.

Maybe a "isCollapsible" tag is for css styling will be better, rather than styling everything with the sectionHeader class.

**Comment by MichaelEbert** [comment]
Will proabbly override on subpages if I need to, since the "isCollapsible" and "sectionTitle" otherwise go well together
