### ISSUE TITLE
[Save] Links to nowhere

### ISSUE THREAD

**Issue by lukepk** [MichaelEbert/OblivionProgressTracker#54]
Clicking on a [Save] in the speedrun guide links to [https://en.uesp.net/wiki/Oblivion:](https://en.uesp.net/wiki/Oblivion:)

**Comment by MichaelEbert** [comment]
Arena fights also currently link to bogus links. Do we want to add some kind of "nolink" attribute to the json? or what?

**Comment by MichaelEbert** [comment]
Nirnroot will also have bad links.

**Comment by MichaelEbert** [comment]
Fixed by #130
