### ISSUE TITLE
Speech appears on right side on mobile

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#63]
On smaller screens (aka mobile), it can be useful to disable iframe because you don't have much room anyways. But speech appears in that column and makes everything else narrower.

**Comment by Muggyfox1** [comment]
Since we can progress via spacebar/tapping now, do you think we could put a banner on the bottom of the page that says something like "speech enabled. press spacebar/tap to read next line."

**Comment by Muggyfox1** [comment]
resolve on #66
