### ISSUE TITLE
better way to increase iframe width.

### ISSUE THREAD

**Issue by Muggyfox1** [MichaelEbert/OblivionProgressTracker#93]
To increase iframe width you have to click and drag, and it runs into the end of the screen before it increases in width too much.

Is there a way we can put the resize handle on the left? Or wrap the mouse around the screen so we can increase width in one go instead of a bunch of little drags?

**Comment by MichaelEbert** [comment]
Possible, but we'd have to move to a javascript solution for that.

**Comment by MichaelEbert** [comment]
Partial solution is current settings page, where you can specify default width in vw and it will stick.

**Comment by MeemawHustlin** [comment]
This is now being addressed in draft PR #298
