### ISSUE TITLE
Make nirnroot and location use jsondata trees instead of arrays in map.js

### ISSUE THREAD

**Issue by MichaelEbert** [MichaelEbert/OblivionProgressTracker#95]
currently nirnroot and location are copied in to an array for display. we should just loop over all the elements in the hive instead. This will involve a minor bit of refactoring to get rid of the indices, and just use objects directly.

**Comment by MichaelEbert** [comment]
Also we need to add in a formid - id mapping for nirnroot and locations to save them

**Comment by Muggyfox1** [comment]
How do we get the formid for nornroots? Wont it all be the same Id?

**Comment by MichaelEbert** [comment]
each nirn has a unique ref id. see issue #44
